language: python
sudo: required

env:
  - TOXENV=py25
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

os:
  - linux

install:
  - pip install tox
  - pip install thutils

script: 
  - tox
